apiVersion: apps/v1
kind: Deployment

metadata:
  name: nodejs
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: mahmoudmselim/nodejs:latest
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
